name: 'Jira create and set fix version'
description: 'Intended for CD, this action creates and sets the given version as fix version in Jira Cloud for given issue'
branding:
  icon: "cloud"
  color: "blue"

inputs:
  domain:
    description: 'Domain name of the Jira cloud instance (e.g. your-domain.atlassian.net)'
    required: true
  username:
    description: 'Jira Username'
    required: true
  password:
    description: 'Jira Personal Access Token'
    required: true
  versionName:
    description: 'The name of the Version to use'
    required: true
  issueKeys:
    description: 'The key(s) of the issue(s) that is to be updated. If multiple are used, separate them with a comma (e.g. "TEST-1,TEST-2")'
    required: true
  versionDescription:
    description: 'The description of the Version (default: "CD version")'
    required: false
  versionArchived:
    description: 'Mark the new version as archived (default: false)'
    required: false
  versionReleased:
    description: 'Mark the new version as released (default: false)'
    required: false
  projectKey:
    description: 'The project the new version should be created in (default: project key of the first issue key)'
    required: false
runs:
  using: 'node20'
  main: 'index.js'
